name: 'jaffle_shop'
version: '1.0.0'
config-version: 2
require-dbt-version: [">=0.17.0"]

profile: dbt-databricks-demo-compute

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"
clean-targets:
    - "target"
    - "dbt_modules"

# TODO put this in a properties file in seeds dir.
seeds:
  jaffle_shop:
    jaffle_shop_customers:
      +schema: jaffle_shop
    jaffle_shop_orders:
      +schema: jaffle_shop
    stripe_payments:
      +schema: stripe 
